-- Phase 1-1: TBL_MEMBER ROLE 컬럼에 DRIVER 추가
ALTER TABLE TBL_MEMBER MODIFY COLUMN ROLE ENUM('ADMIN','USER','DRIVER') NOT NULL DEFAULT 'USER';

-- Phase 1-2: WebOrderMast에 배송기사 필드 추가
ALTER TABLE sa_order_mast ADD COLUMN WEB_DRIVER_ID BIGINT NULL;
ALTER TABLE sa_order_mast ADD COLUMN WEB_CONFIRMED_AT DATETIME NULL;
ALTER TABLE sa_order_mast ADD COLUMN WEB_DRIVER_SIGN MEDIUMTEXT NULL;
ALTER TABLE sa_order_mast ADD COLUMN WEB_DRIVER_SIGN_AT DATETIME NULL;
ALTER TABLE sa_order_mast ADD COLUMN WEB_CUST_SIGN MEDIUMTEXT NULL;
ALTER TABLE sa_order_mast ADD COLUMN WEB_CUST_SIGN_AT DATETIME NULL;

-- Phase 1-3: 배송 사진 테이블
CREATE TABLE IF NOT EXISTS TBL_DELIVERY_PHOTO (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    ORDER_KEY VARCHAR(100) NOT NULL,
    FILE_PATH VARCHAR(500) NOT NULL,
    ORIGINAL_NAME VARCHAR(300),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(100),
    PRIMARY KEY (ID),
    INDEX IDX_DELIVERY_PHOTO_ORDER_KEY (ORDER_KEY)
);

-- Phase 1-4: 알림 테이블
CREATE TABLE IF NOT EXISTS TBL_NOTIFICATION (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    MEMBER_ID BIGINT NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    MESSAGE VARCHAR(500),
    ORDER_KEY VARCHAR(100),
    IS_READ BOOLEAN DEFAULT FALSE,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    INDEX IDX_NOTIFICATION_MEMBER (MEMBER_ID),
    INDEX IDX_NOTIFICATION_READ (MEMBER_ID, IS_READ)
);
