-- Feature #9: 미등록 품목 주문하기

-- 1. co_custom_item 테이블 생성 (Web DB)
CREATE TABLE IF NOT EXISTS co_custom_item (
  CUSTOM_ITEM_CODE      BIGINT AUTO_INCREMENT PRIMARY KEY,
  CUSTOM_ITEM_CUST      INT NOT NULL,
  CUSTOM_ITEM_HNAM      VARCHAR(100) NOT NULL,
  CUSTOM_ITEM_DESC      VARCHAR(500) NULL,
  CUSTOM_ITEM_SPEC      VARCHAR(200) NULL,
  CUSTOM_ITEM_UNIT      VARCHAR(50) NULL,
  CUSTOM_ITEM_VDIV      TINYINT(3) NOT NULL DEFAULT 1,
  CUSTOM_ITEM_SRATE     DECIMAL(18,2) NOT NULL DEFAULT 0,
  CUSTOM_ITEM_SLRATE    DECIMAL(18,2) NOT NULL DEFAULT 0,
  CUSTOM_ITEM_SLRDATE   CHAR(8) NOT NULL DEFAULT '',
  CUSTOM_ITEM_REMARK    VARCHAR(200) NULL,
  CUSTOM_ITEM_USE       TINYINT(3) NOT NULL DEFAULT 1,
  CUSTOM_ITEM_FDATE     DATETIME NULL,
  CUSTOM_ITEM_FUSER     VARCHAR(20) NULL,
  CUSTOM_ITEM_LDATE     DATETIME NULL,
  CUSTOM_ITEM_LUSER     VARCHAR(20) NULL,
  INDEX idx_cust_use (CUSTOM_ITEM_CUST, CUSTOM_ITEM_USE)
);

-- 2. co_custom_item_image 테이블 생성 (Web DB)
CREATE TABLE IF NOT EXISTS co_custom_item_image (
  id              BIGINT AUTO_INCREMENT PRIMARY KEY,
  custom_item_id  BIGINT NOT NULL,
  file_path       VARCHAR(500) NOT NULL,
  original_name   VARCHAR(255) NULL,
  sort_order      INT NOT NULL DEFAULT 0,
  is_thumbnail    TINYINT(1) NOT NULL DEFAULT 0,
  created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_custom_item (custom_item_id)
);

-- 3. sa_cart_item에 custom_item_id 컬럼 추가
ALTER TABLE sa_cart_item ADD COLUMN custom_item_id BIGINT NULL;
ALTER TABLE sa_cart_item MODIFY COLUMN item_code INT NULL;

-- 4. sa_order_tran에 ORDER_TRAN_CUSTOMITEM 컬럼 추가
ALTER TABLE sa_order_tran ADD COLUMN ORDER_TRAN_CUSTOMITEM BIGINT NULL;
